Kouncil - artykuły do wersji 1.5 i 1.6
Kouncil/kouncil.github.io pull request #4
Opened 2023-10-23 12:10 UTC by pbelke

2023-10-23 12:31 UTC, pogoma commented on assets/img/posts/2023-10-22-kouncil-1.5/kouncil-1.5.png
Obrazek, który ilustruje zawartość artykułu powinien mieć aspect ratio 4:3 - inaczej będzie się brzydko skalował na liście artykułów

2023-10-23 12:31 UTC, pogoma commented on assets/img/posts/2023-10-22-kouncil-1.6/kouncil-1.6.png
Obrazek, który ilustruje zawartość artykułu powinien mieć aspect ratio 4:3 - inaczej będzie się brzydko skalował na liście artykułów

2023-10-23 12:34 UTC, pogoma commented on _posts/en/2023-10-22-kafka-1.5.md
Nazwa pliku, w którym jest artykuł wprost tłumaczy się na ścieżkę. Czy nie lepiej by było tutaj zamienić kafkę kouncilem?

2023-10-23 12:34 UTC, pogoma commented on _posts/en/2023-10-22-kafka-1.5.md
> +Working on the latest version of Kouncil, we focused on improving the application security and added the possibility of safely connecting with Kafka brokers.
Ten artykuł dotyczy konkretnej wersji, czy używanie słówka latest jest tutaj trafione?

2023-10-23 12:35 UTC, pogoma commented on _posts/en/2023-10-22-kafka-1.5.md
> +## Autentykacja
Ani to po angielsku ani po polsku, chyba powinno być "authentication"

2023-10-23 12:36 UTC, pogoma commented on _posts/en/2023-10-22-kafka-1.5.md
> +We have prepared 4 authentication options:
"authentication options" - IMO bardziej by pasowało "authentication methods"

2023-10-23 12:44 UTC, pogoma commented on _posts/en/2023-10-22-kafka-1.5.md
> +![2019-09-05-Kafka-DLQ-Strategy01.png](/assets/img/posts/2023-10-22-kouncil-1.5/kouncil-1.5-1.png)
To co się znajduje w nawiasach kwadratowych to tekst alternatywny (wyświetlany kiedy nie można wyświetlić obrazka), w założeniu powinien opisywać to co jest na obrazku, niestety jekyll nie wspiera dodatkowych etykiet pod obrazkami, więc jeśli chcesz taką mieć to należy dodać ją w elemencie z klasą .img-legend (dzięki temu mamy pewność, że wszystkie etykiety we wszystkich postach będą wygladać tak samo), czyli w twoim przypadku powinno to wyglądać tak:
```
![Login screen for SSO authentication](/assets/img/posts/2023-10-22-kouncil-1.5/kouncil-1.5-2.png)
<span class="img-legend">Login screen for SSO authentication</span>
```

2023-10-23 12:44 UTC, pogoma commented on _posts/en/2023-10-22-kafka-1.5.md
> +![2019-09-05-Kafka-DLQ-Strategy01.png](/assets/img/posts/2023-10-22-kouncil-1.5/kouncil-1.5-2.png)
ta sama uwaga co wyżej

2023-10-23 12:47 UTC, pogoma commented on _posts/en/2023-10-22-kafka-1.5.md
> +#### These changes make working with Kouncil even more secure.
Nie używamy nagłówków do formatowania tekstu. Nagłówki są używane do nawigacji po tekście. Dodatkowo, dzięki nim zewnętrzne witryny (np wyszukiwarki) mogą odsyłać do konkretnego miejsca. 

Prawdopodobnie to co chciałeś osiągnąć możesz zrobić za pomocą takiego kodu:
```
## Effect
**These changes make working with Kouncil even more secure.**
```

2023-10-23 12:47 UTC, pogoma commented on _posts/en/2023-10-22-kafka-1.5.md
> +* In-Memory (with a predefined administrative user)
czy na końcu każdego punktu nie powinno być przecinka, a w ostatnim kropeczka?

2023-10-23 12:48 UTC, pogoma commented on _posts/en/2023-10-22-kafka-1.5.md
> +If you want to check out a sample configuration, refer to our documentation, [Authentication](https://docs.kouncil.io/getting-started/deployment#authentication) and [SASL Authentication](https://docs
"refer to our documentation," - tu chyba powinien być dwukropek a nie przecinek

2023-10-23 12:49 UTC, pogoma commented on _posts/en/2023-10-22-kafka-1.5.md
> +We also encourage you to test and provide feedback via the [form](https://kouncil.io/contact-us/) or on [GitHub](https://github.com/consdata/kouncil).
ja bym to zdanie zmienił na:
```
We also encourage you to test and provide feedback via the [contact form](https://kouncil.io/contact-us/) or on [our GitHub](https://github.com/consdata/kouncil).
```

2023-10-23 12:50 UTC, pogoma commented on _posts/en/2023-10-22-kafka-1.6.md
> +date:      2023-10-22 6:00:00 +0100
dodałbym jedną godzinę żeby na liście pojawiło się na 100% po artykule dotyczącym poprzedniej wersji

2023-10-23 13:09 UTC, pogoma commented on _posts/en/2023-10-22-kafka-1.6.md
> +The most important change in the new version of Kouncil is the configuration of permissions, which allows precise control of user access to particular functions. In addition, in an effort to continuo
Czy nie warto by operować na konkretnej wersji zamiast na "new"?

2023-10-23 13:10 UTC, pogoma commented on _posts/en/2023-10-22-kafka-1.6.md
> +* users with administrative roles gain access to broker and consumer group screens
czy na końcu każdego punktu nie powinno być przecinka, a w ostatnim kropeczka?

2023-10-23 13:12 UTC, pogoma commented on _posts/en/2023-10-22-kafka-1.6.md
> +![2019-09-05-Kafka-DLQ-Strategy01.png](/assets/img/posts/2023-10-22-kouncil-1.6/kouncil-1.6-1.png)
Ta sama uwaga do obrazków co w artykule odnośnie wersji 1.5

2023-10-23 13:12 UTC, pogoma commented on _posts/en/2023-10-22-kafka-1.6.md
> +## Effect
Nie używamy nagłówków do formatowania tekstu. Nagłówki są używane do nawigacji po tekście. Dodatkowo, dzięki nim zewnętrzne witryny (np wyszukiwarki) mogą odsyłać do konkretnego miejsca.

Prawdopodobnie to co chciałeś osiągnąć możesz zrobić za pomocą takiego kodu:
```
## Effect
**As a result, you can grant users access to role-specific functions.**
```

2023-10-23 13:13 UTC, pogoma commented on _posts/en/2023-10-22-kafka-1.6.md
> +We also encourage you to test and provide feedback via the [form](https://kouncil.io/contact-us/) or on [GitHub](https://github.com/consdata/kouncil).
Zmieniłbym "form" na "contact form" i "GitHub" na "our GitHub"

2023-10-24 13:33 UTC, pogoma approved these changes

2023-12-11 10:10 UTC, ynleborg requested changes

2023-12-11 10:10 UTC, ynleborg commented on _posts/pl/2023-10-22-kouncil-1.5.md
> +## Autentykacja
pl: Uwierzytelnianie (tutaj i w dwóch innych miejscach w artykule)

2023-12-11 10:10 UTC, ynleborg commented on _posts/pl/2023-10-22-kouncil-1.5.md
> +* In-Memory (z predefiniowanym użytkownikiem administracyjny),
administracyjny**m**

2023-12-11 10:10 UTC, ynleborg commented on _posts/pl/2023-10-22-kouncil-1.5.md
> +Dzięki nowej funkcji możesz zabezpieczyć swoich brokerów mechanizmem autentykacji SASL. Wystarczy, że podczas konfiguracji klastra Kafki w Kouncil podasz dane logowania do brokera, a Kouncil uwierzyt
myśle, że to za duży skrót myślowy. Włączenie uwierzytelniania na Kouncilu nie gwarantuje zabezpieczenia brokerów. Ta konfiguracja musi być wcześniej wdrożona na samym brokerze.

2023-12-11 10:10 UTC, ynleborg commented on _posts/en/2023-10-22-kouncil-1.5.md
> +With this new feature, you can secure your brokers with the SASL authentication mechanism. All you need to do is enter your broker login details when configuring your Kafka cluster in Kouncil, and Ko
tutaj podobnie jak w PL, trochę bym to przeredagował.

2023-12-11 10:10 UTC, ynleborg commented on _posts/pl/2023-10-22-kouncil-1.6.md
> +Jeśli chcesz dowiedzieć się więcej na temat zastosowanych w Kouncil metod autentykacji zachęcamy do przeczytania [artykułu](https://blog.kouncil.io/2023/10/22/kafka-1.5.html) dotyczącego zmian w popr
uwierzytelnianie tutaj i akapit niżej

2023-12-11 10:10 UTC, ynleborg commented on _posts/pl/2023-10-22-kouncil-1.6.md
> +## Konfiguracja uprawnień
To jest de factor autoryzacja (eng. authorization) ale w tekście nie pada ani razu, ani w PL ani w ENG poza tagami i linkami. Nie upieram się, bo opis jest prawidłowy, ale jak by się udało wpleść gdzie te terminy to by było ok. Może w tytule sekcji?

2023-12-11 10:10 UTC, ynleborg commented on _posts/en/2023-10-22-kouncil-1.6.md
> +* users with the editor role can view topic screens, track messages, and send communications to selected topics,
messages  zamiast communications

2023-12-11 10:10 UTC, ynleborg commented on _posts/en/2023-10-22-kouncil-1.6.md
> +* users with read-only permission can view messages and data on the topic screens.
"messages" to są "data", więc masło maślane

2023-12-11 10:10 UTC, ynleborg commented on _posts/en/2023-10-22-kouncil-1.6.md
> +Thanks to a new function for granting permissions, a logged-in user has access to all Kouncil functions defined for their assigned role.
Kouncil's

2023-12-12 09:02 UTC, ynleborg approved these changes

2023-12-12 16:37 UTC, merged